### ISSUE TITLE
New upstream version available

### ISSUE THREAD

**Issue by jedwabny** [arturdm/openwrt-niceshaper#1]
There is a new, 1.2.3, version available. It contains workaround which makes possible to run with kernels compiled without CONFIG_CLS_U32_PERF feature. Kernel in the latest OpenWRT seems to be compiled in such previously unsupported way.

I've proceeded with building new package and binary is running successfully on 15.05.1 generic ar71xx.

**Comment by arturdm** [comment]
Hi @mjd80,

I bumped the version to 1.2.3 in #2.

Can you also check my patch there? It changes `src/config.cc` file so it handles interface names with dashes in their names (e.g. `br-lan`). If it looks good you can also apply it to upstream.
