### ISSUE TITLE
New upstream version 1.2.4 available

### ISSUE THREAD

**Issue by jedwabny** [arturdm/openwrt-niceshaper#3]
There is a new, 1.2.4, version available. It contains the iface with dashes issue fixed.

I've already built package, for my home router (ar71xx/generic), using your build scripts and it works without problems. Thanks!

**Comment by arturdm** [comment]
@mjd80 I made a PR with the version bumped to 1.2.4 (#4). This version does not need the patch anymore, right?

**Comment by jedwabny** [comment]
true, patch is not needed for this version.

**Comment by arturdm** [comment]
Thank you. #4 merged.
